### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [8]:
# Dependencies and Setup
import pandas as pd
import numpy as np

#Make all floating number 2 decimal number format 
pd.options.display.float_format = '{:.2f}'.format

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
data = pd.read_csv(file_to_load)
data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [ ]:
total_number_players = data.SN.nunique()
total_number_players

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [ ]:
# Calculate everything 
players = data.SN.nunique()
avr_price = data.Price.mean()
unique_items = data['Item Name'].nunique()

#Create a dictionary for results

summary = {'Calculations': ['Unique players', 'Average price', 'Unique items'],
           'Results': [players, avr_price, unique_items]   
}

#Create a new data frame
df_summary = pd.DataFrame.from_dict(summary)

#Format everything and print the result
df_summary

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [ ]:
all_gender = data['Gender'].count()
males = data['Gender'][data['Gender'] == 'Male'].count()
females = data['Gender'][data['Gender'] == 'Female'].count()
other = data['Gender'][data['Gender'] == 'Other / Non-Disclosed'].count()


def percentage_gender(x):
    percentage = x / all_gender * 100
    return(f'Percentage of total {int(percentage)}%')


males = percentage_gender(males)
females = percentage_gender(females)
other = percentage_gender(other)

gender_df = pd.DataFrame({'stasts': [males, females, other]})
gender_df


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [ ]:
#Create a groupby object
gender_group = data.groupby('Gender')

#Make calculations
avr_gender = gender_group.mean()
sum_gender = gender_group.sum()
count_gender = gender_group.count()

#Display summary in DataFrame
mega_df = pd.DataFrame({
    'Average price': avr_gender['Price'],
    'Total purchased': sum_gender['Price'],
    'Number of transactions': count_gender['Price']
})

mega_df

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [43]:
#Create brackets for the bins
ages = [1,10,20,40]

#Create bins
bins_categories = ['baby','teenager', 'adult']

#Cut bins
data['Age Categories'] = pd.cut(data['Age'], ages, labels = bins_categories)

#Calculate everything
all_ages = data['Age Categories'].count()
baby = data['Age Categories'][data['Age Categories'] == 'baby'].count()
teenager = data['Age Categories'][data['Age Categories'] == 'teenager'].count()
adult = data['Age Categories'][data['Age Categories'] == 'adult'].count()


def percentage_gender(x):
    percentage = x / all_ages * 100
    return(f'{int(percentage)}%')
    


baby_p = percentage_gender(baby)
teenager_p = percentage_gender(teenager)
adult_p = percentage_gender(adult)


summary_age_category = pd.DataFrame({'Category': ['Baby','Teenager','Adult'],
                        'Number': [baby,teenager, adult],
                        'Percentage':[baby_p, teenager_p, adult_p]
})

summary_age_category

   Category  Number Percentage
0      Baby      32         4%
1  Teenager     254        32%
2     Adult     487        63%

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [3]:
#Upload fresh data 
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
data = pd.read_csv(file_to_load)

#Create brackets for the bins
ages = [1,10,20,40]

#Create bins
bins_categories = ['baby','teenager', 'adult']

#Cut bins
data['Age Categories'] = pd.cut(data['Age'], ages, labels = bins_categories)


#Group by Age Categories
age_group = data.groupby('Age Categories')

#Make calculations
avr_age = age_group.mean()
sum_age = age_group.sum()
count_age = age_group.count()

#Display summary in DataFrame
mega_df = pd.DataFrame({
    'Average price': avr_age['Price'],
    'Total purchased': sum_age['Price'],
    'Number of transactions': count_age['Price']
})

mega_df

                Average price  Total purchased  Number of transactions
Age Categories
baby                     3.40           108.96                      32
teenager                 3.06           778.16                     254
adult                    3.02          1471.12                     487

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [34]:
mega_sum = mega_df.sum()
bigdata = mega_df.append(mega_sum, ignore_index=True)
bigdata

   Average price  Total purchased  Number of transactions
0           3.40           108.96                   32.00
1           3.06           778.16                  254.00
2           3.02          1471.12                  487.00
3           9.49          2358.24                  773.00

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [57]:
item_sum = data.groupby(["Item ID", 'Item Name']).sum()

item_mean = data.groupby(["Item ID", 'Item Name']).mean()

item_count = data.groupby(["Item ID", 'Item Name']).count()

total_item = pd.DataFrame({"Items Sum": item_sum['Price'],
                          "Item Average": item_mean['Price'],
                          "Quanitity of items": item_count['Price']})

total_item.head()

                            Items Sum  Item Average  Quanitity of items
Item ID Item Name
0       Splinter                 5.12          1.28                   4
1       Crucifer                 9.78          3.26                   3
2       Verdict                 14.88          2.48                   6
3       Phantomlight            14.94          2.49                   6
4       Bloodlord's Fetish       8.50          1.70                   5

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [60]:
total_item.sort_values('Items Sum', ascending=False)

,,Items Sum,Item Average,Quanitity of items
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",50.76,4.23,12
82,Nirvana,44.10,4.90,9
145,Fiery Glass Crusader,41.22,4.58,9
92,Final Critic,39.04,4.88,8
103,Singed Scalpel,34.80,4.35,8
59,"Lightning, Etcher of the King",33.84,4.23,8
108,"Extraction, Quickblade Of Trembling Hands",31.77,3.53,9
78,"Glimmer, Ender of the Moon",30.80,4.40,7
72,Winter's Bite,30.16,3.77,8
60,Wolf,28.32,3.54,8
179,"Wolf, Promise of the Moonwalker",26.88,4.48,6
160,Azurewrath,26.40,4.40,6
25,Hero Cane,26.10,4.35,6
37,"Shadow Strike, Glory of Ending Hope",25.28,3.16,8
139,"Mercy, Katana of Dismay",24.70,4.94,5
128,"Blazeguard, Reach of Eternity",24.55,4.91,5
138,"Peacekeeper, Wit of Dark Magic",23.70,4.74,5
141,Persuasion,22.33,3.19,7
87,"Deluge, Edge of the West",22.15,4.43,5
159,"Oathbreaker, Spellblade of Trials",21.56,3.08,7
136,Ghastly Adamantite Protector,21.48,3.58,6
65,Conqueror Adamantite Mace,21.20,4.24,5
101,Final Critic,20.95,4.19,5
102,Avenger,20.64,3.44,6
133,Faith's Scimitar,20.45,4.09,5
39,"Betrayal, Whisper of Grieving Widows",19.70,3.94,5
111,Misery's End,19.56,4.89,4
165,Bone Crushing Silver Skewer,19.44,4.86,4
75,Brutality Ivory Warmace,19.36,2.42,8
52,Hatred,19.36,4.84,4
...,...,...,...,...
124,Venom Claymore,5.16,1.29,4
0,Splinter,5.12,1.28,4
155,War-Forged Gold Deflector,5.05,1.01,5
48,"Rage, Legacy of the Lone Victor",4.96,2.48,2
158,"Darkheart, Butcher of the Champion",4.90,2.45,2
51,Endbringer,4.66,4.66,1
134,Undead Crusader,4.50,4.50,1
30,Stormcaller,4.42,2.21,2
135,Warped Diamond Crusader,4.20,1.40,3
91,Celeste,4.17,4.17,1
177,"Winterthorn, Defender of Shifting Worlds",4.16,2.08,2
70,Hope's End,4.12,1.03,4
115,Spectral Diamond Doomblade,4.08,2.04,2
69,"Frenzy, Defender of the Harvest",3.96,1.98,2
47,"Alpha, Reach of Ending Hope",3.58,3.58,1
180,Stormcaller,3.36,3.36,1
27,"Riddle, Tribute of Ended Dreams",3.30,3.30,1
183,Dragon's Greatsword,3.27,1.09,3
31,Trickster,3.10,1.55,2
168,"Sun Strike, Jaws of Twisted Visions",2.96,1.48,2
90,Betrayer,2.94,2.94,1
33,Curved Axe,2.32,1.16,2
26,Unholy Wand,2.24,1.12,2
118,"Ghost Reaver, Longsword of Magic",2.17,2.17,1
28,"Flux, Destroyer of Due Diligence",2.12,1.06,2
125,Whistling Mithril Warblade,2.00,1.00,2
126,Exiled Mithril Longsword,2.00,2.00,1
23,Crucifer,1.99,1.99,1
104,Gladiator's Glaive,1.93,1.93,1
42,The Decapitator,1.75,1.75,1